--ax.option:Add("persistence_physgun", ax.type.bool, false, {
    --description = "Enable/Disable Physgun interactions with persisted Props",
	--category = "persistence",
	--subCategory = "general",
--})
